---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-express-prod
  namespace: prod
  labels:
    app: argo-express-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-express-prod
  template:
    metadata:
      labels:
        app: argo-express-prod
    spec:
      containers:
        - name: argo-express-api
          image: nthskyradiated/argo-express-api:v1.1
          ports:
            - containerPort: 8080
  revisionHistoryLimit: 5
