---
apiVersion: v1
kind: Secret
metadata:
  name: express-api-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:nthskyradiated/express-api.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBNNKQeY0p+JKRj4H/itWP1jxP0F+AxsbMF/dbGdpVibgAAAKBgp1DWYKdQ
    1gAAAAtzc2gtZWQyNTUxOQAAACBNNKQeY0p+JKRj4H/itWP1jxP0F+AxsbMF/dbGdpVibg
    AAAEBY9bRnv7FjD9HtWo//IHuadb7pzY1Pd92m7D4kD07Ul000pB5jSn4kpGPgf+K1Y/WP
    E/QX4DGxswX91sZ2lWJuAAAAGGFuZHkucGFuZGFhbkBvdXRsb29rLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
